### PR TITLE
Feature: add support for angular 1.4

### PR DESCRIPTION
**Pull request by edoparearyee**

### CODE REVIEW

**Comment by edoparearyee** [comment]
@jamesjwarren can you pls have a :eyes:

**Comment by jamesjwarren** [comment]
@edwardoparearyee has this been tested on angular 1.5?

**Comment by edoparearyee** [comment]
@jamesjwarren good point, just checked and 1.5 isn't out yet as i thought it was. Will only add 1.4 for now

**Comment by edoparearyee** [comment]
@jamesjwarren should be ready now

**Comment by jamesjwarren** [comment]
:+1:

**Pull request merged**
